### ISSUE TITLE
Js

### ISSUE THREAD

**Issue by AkhmadBabaev** [guipure/hotel-rooms-finder#12]
Файлы компонентов которые экспортируют класс имеются в стиле PascalCase. То есть date-dropdown.js становится DateDropdown.js и так со всеми.

**Comment by AkhmadBabaev** [comment]
Имена защищенных методов и свойств классов должны начинается с нижнего подчеркивания _.

**Comment by AkhmadBabaev** [comment]
Когда в условии отсутствует вариант else, а так же одна строка всего то будет круче писать так 
![image](https://user-images.githubusercontent.com/51095975/90270731-5789d200-de63-11ea-858b-83f70f43821b.png)

Скрин с файла date-dropdown.js.

**Comment by guipure** [comment]
Заменил if на && только там, где выражение можно было уложить в одну строку до 100 символов. Когда строчек несколько, я думаю, что нагляднее будет с if

**Comment by AkhmadBabaev** [comment]
> Заменил if на && только там, где выражение можно было уложить в одну строку до 100 символов. Когда строчек несколько, я думаю, что нагляднее будет с if

Отлично, значит ты уловил всю суть.

**Comment by AkhmadBabaev** [comment]
https://github.com/guipure/hotel-rooms-finder/blob/19fcec4f7fdba6e3f3766eba5a2751b727d69ec2/src/blocks/checkbox-list/CheckboxList.js#L1-L18

Объявление переменных в конструкторе не желательно.
Привязку событий лучше делать в отдельном методе, так же и поиск элементов.
Обработчик событий должен именоваться по шаблону - handleElementNameEventName пример handleSliderClick.
