### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AkhmadBabaev** [guipure/hotel-rooms-finder#14]
Поле MASKED TEXT FIELD страницы form-elements работает некорректно. Получается ввести только первые две цифры.

**Comment by guipure** [comment]
Какую именно дату не получается ввести? Запрещено вводить первую цифру ДД не равную 0, 1, 2, или 3 и первую цифру ММ не равную 0 или 1.

**Comment by AkhmadBabaev** [comment]
Виноват, совсем не подумал про форматирование, просто по клавишам стучал 😅. Кликнув мышью можно ввести значения и туда куда не получилось добраться и немного смутило то что можно ввести не валидный месяц типа 19.

**Comment by AkhmadBabaev** [comment]
Навигационное меню в шапке сайте нужно трансформировать в гамбургер меню на мобильных устройствах.
